//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab11_ASP_asmx_web_form.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.SSLServiceSoap")]
    public interface SSLServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add", ReplyAction="*")]
        int Add(int x, int y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add", ReplyAction="*")]
        System.Threading.Tasks.Task<int> AddAsync(int x, int y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetLastSum", ReplyAction="*")]
        int GetLastSum();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetLastSum", ReplyAction="*")]
        System.Threading.Tasks.Task<int> GetLastSumAsync();
        
        // CODEGEN: Контракт генерации сообщений с именем GetCalculationsResult из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCalculations", ReplyAction="*")]
        Lab11_ASP_asmx_web_form.ServiceReference1.GetCalculationsResponse GetCalculations(Lab11_ASP_asmx_web_form.ServiceReference1.GetCalculationsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCalculations", ReplyAction="*")]
        System.Threading.Tasks.Task<Lab11_ASP_asmx_web_form.ServiceReference1.GetCalculationsResponse> GetCalculationsAsync(Lab11_ASP_asmx_web_form.ServiceReference1.GetCalculationsRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем GetCalculationsApllResult из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCalculationsApll", ReplyAction="*")]
        Lab11_ASP_asmx_web_form.ServiceReference1.GetCalculationsApllResponse GetCalculationsApll(Lab11_ASP_asmx_web_form.ServiceReference1.GetCalculationsApllRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCalculationsApll", ReplyAction="*")]
        System.Threading.Tasks.Task<Lab11_ASP_asmx_web_form.ServiceReference1.GetCalculationsApllResponse> GetCalculationsApllAsync(Lab11_ASP_asmx_web_form.ServiceReference1.GetCalculationsApllRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DropApp", ReplyAction="*")]
        void DropApp();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DropApp", ReplyAction="*")]
        System.Threading.Tasks.Task DropAppAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetLastSub", ReplyAction="*")]
        int GetLastSub();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetLastSub", ReplyAction="*")]
        System.Threading.Tasks.Task<int> GetLastSubAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Sub", ReplyAction="*")]
        int Sub(int x, int y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Sub", ReplyAction="*")]
        System.Threading.Tasks.Task<int> SubAsync(int x, int y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Mul", ReplyAction="*")]
        int Mul(int x, int y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Mul", ReplyAction="*")]
        System.Threading.Tasks.Task<int> MulAsync(int x, int y);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCalculationsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCalculations", Namespace="http://tempuri.org/", Order=0)]
        public Lab11_ASP_asmx_web_form.ServiceReference1.GetCalculationsRequestBody Body;
        
        public GetCalculationsRequest() {
        }
        
        public GetCalculationsRequest(Lab11_ASP_asmx_web_form.ServiceReference1.GetCalculationsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetCalculationsRequestBody {
        
        public GetCalculationsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCalculationsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCalculationsResponse", Namespace="http://tempuri.org/", Order=0)]
        public Lab11_ASP_asmx_web_form.ServiceReference1.GetCalculationsResponseBody Body;
        
        public GetCalculationsResponse() {
        }
        
        public GetCalculationsResponse(Lab11_ASP_asmx_web_form.ServiceReference1.GetCalculationsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCalculationsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Lab11_ASP_asmx_web_form.ServiceReference1.ArrayOfString GetCalculationsResult;
        
        public GetCalculationsResponseBody() {
        }
        
        public GetCalculationsResponseBody(Lab11_ASP_asmx_web_form.ServiceReference1.ArrayOfString GetCalculationsResult) {
            this.GetCalculationsResult = GetCalculationsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCalculationsApllRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCalculationsApll", Namespace="http://tempuri.org/", Order=0)]
        public Lab11_ASP_asmx_web_form.ServiceReference1.GetCalculationsApllRequestBody Body;
        
        public GetCalculationsApllRequest() {
        }
        
        public GetCalculationsApllRequest(Lab11_ASP_asmx_web_form.ServiceReference1.GetCalculationsApllRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetCalculationsApllRequestBody {
        
        public GetCalculationsApllRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCalculationsApllResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCalculationsApllResponse", Namespace="http://tempuri.org/", Order=0)]
        public Lab11_ASP_asmx_web_form.ServiceReference1.GetCalculationsApllResponseBody Body;
        
        public GetCalculationsApllResponse() {
        }
        
        public GetCalculationsApllResponse(Lab11_ASP_asmx_web_form.ServiceReference1.GetCalculationsApllResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCalculationsApllResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Lab11_ASP_asmx_web_form.ServiceReference1.ArrayOfString GetCalculationsApllResult;
        
        public GetCalculationsApllResponseBody() {
        }
        
        public GetCalculationsApllResponseBody(Lab11_ASP_asmx_web_form.ServiceReference1.ArrayOfString GetCalculationsApllResult) {
            this.GetCalculationsApllResult = GetCalculationsApllResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SSLServiceSoapChannel : Lab11_ASP_asmx_web_form.ServiceReference1.SSLServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SSLServiceSoapClient : System.ServiceModel.ClientBase<Lab11_ASP_asmx_web_form.ServiceReference1.SSLServiceSoap>, Lab11_ASP_asmx_web_form.ServiceReference1.SSLServiceSoap {
        
        public SSLServiceSoapClient() {
        }
        
        public SSLServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SSLServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SSLServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SSLServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int Add(int x, int y) {
            return base.Channel.Add(x, y);
        }
        
        public System.Threading.Tasks.Task<int> AddAsync(int x, int y) {
            return base.Channel.AddAsync(x, y);
        }
        
        public int GetLastSum() {
            return base.Channel.GetLastSum();
        }
        
        public System.Threading.Tasks.Task<int> GetLastSumAsync() {
            return base.Channel.GetLastSumAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Lab11_ASP_asmx_web_form.ServiceReference1.GetCalculationsResponse Lab11_ASP_asmx_web_form.ServiceReference1.SSLServiceSoap.GetCalculations(Lab11_ASP_asmx_web_form.ServiceReference1.GetCalculationsRequest request) {
            return base.Channel.GetCalculations(request);
        }
        
        public Lab11_ASP_asmx_web_form.ServiceReference1.ArrayOfString GetCalculations() {
            Lab11_ASP_asmx_web_form.ServiceReference1.GetCalculationsRequest inValue = new Lab11_ASP_asmx_web_form.ServiceReference1.GetCalculationsRequest();
            inValue.Body = new Lab11_ASP_asmx_web_form.ServiceReference1.GetCalculationsRequestBody();
            Lab11_ASP_asmx_web_form.ServiceReference1.GetCalculationsResponse retVal = ((Lab11_ASP_asmx_web_form.ServiceReference1.SSLServiceSoap)(this)).GetCalculations(inValue);
            return retVal.Body.GetCalculationsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Lab11_ASP_asmx_web_form.ServiceReference1.GetCalculationsResponse> Lab11_ASP_asmx_web_form.ServiceReference1.SSLServiceSoap.GetCalculationsAsync(Lab11_ASP_asmx_web_form.ServiceReference1.GetCalculationsRequest request) {
            return base.Channel.GetCalculationsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Lab11_ASP_asmx_web_form.ServiceReference1.GetCalculationsResponse> GetCalculationsAsync() {
            Lab11_ASP_asmx_web_form.ServiceReference1.GetCalculationsRequest inValue = new Lab11_ASP_asmx_web_form.ServiceReference1.GetCalculationsRequest();
            inValue.Body = new Lab11_ASP_asmx_web_form.ServiceReference1.GetCalculationsRequestBody();
            return ((Lab11_ASP_asmx_web_form.ServiceReference1.SSLServiceSoap)(this)).GetCalculationsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Lab11_ASP_asmx_web_form.ServiceReference1.GetCalculationsApllResponse Lab11_ASP_asmx_web_form.ServiceReference1.SSLServiceSoap.GetCalculationsApll(Lab11_ASP_asmx_web_form.ServiceReference1.GetCalculationsApllRequest request) {
            return base.Channel.GetCalculationsApll(request);
        }
        
        public Lab11_ASP_asmx_web_form.ServiceReference1.ArrayOfString GetCalculationsApll() {
            Lab11_ASP_asmx_web_form.ServiceReference1.GetCalculationsApllRequest inValue = new Lab11_ASP_asmx_web_form.ServiceReference1.GetCalculationsApllRequest();
            inValue.Body = new Lab11_ASP_asmx_web_form.ServiceReference1.GetCalculationsApllRequestBody();
            Lab11_ASP_asmx_web_form.ServiceReference1.GetCalculationsApllResponse retVal = ((Lab11_ASP_asmx_web_form.ServiceReference1.SSLServiceSoap)(this)).GetCalculationsApll(inValue);
            return retVal.Body.GetCalculationsApllResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Lab11_ASP_asmx_web_form.ServiceReference1.GetCalculationsApllResponse> Lab11_ASP_asmx_web_form.ServiceReference1.SSLServiceSoap.GetCalculationsApllAsync(Lab11_ASP_asmx_web_form.ServiceReference1.GetCalculationsApllRequest request) {
            return base.Channel.GetCalculationsApllAsync(request);
        }
        
        public System.Threading.Tasks.Task<Lab11_ASP_asmx_web_form.ServiceReference1.GetCalculationsApllResponse> GetCalculationsApllAsync() {
            Lab11_ASP_asmx_web_form.ServiceReference1.GetCalculationsApllRequest inValue = new Lab11_ASP_asmx_web_form.ServiceReference1.GetCalculationsApllRequest();
            inValue.Body = new Lab11_ASP_asmx_web_form.ServiceReference1.GetCalculationsApllRequestBody();
            return ((Lab11_ASP_asmx_web_form.ServiceReference1.SSLServiceSoap)(this)).GetCalculationsApllAsync(inValue);
        }
        
        public void DropApp() {
            base.Channel.DropApp();
        }
        
        public System.Threading.Tasks.Task DropAppAsync() {
            return base.Channel.DropAppAsync();
        }
        
        public int GetLastSub() {
            return base.Channel.GetLastSub();
        }
        
        public System.Threading.Tasks.Task<int> GetLastSubAsync() {
            return base.Channel.GetLastSubAsync();
        }
        
        public int Sub(int x, int y) {
            return base.Channel.Sub(x, y);
        }
        
        public System.Threading.Tasks.Task<int> SubAsync(int x, int y) {
            return base.Channel.SubAsync(x, y);
        }
        
        public int Mul(int x, int y) {
            return base.Channel.Mul(x, y);
        }
        
        public System.Threading.Tasks.Task<int> MulAsync(int x, int y) {
            return base.Channel.MulAsync(x, y);
        }
    }
}
